### ISSUE TITLE
聊天页面每次发送新消息，之前的消息位置会变动

### ISSUE THREAD

**Issue by lkasdolka** [HalfdogStudio/BubbleDating#2]
可能与convertView的缓存有关系？
试着去掉缓存看看效果。
实在不行研究下别的IM的源码

**Comment by reverland** [comment]
推荐下别的im，哈哈哈

http://hehehe.im/

**Comment by lkasdolka** [comment]
solution：
1.给convertView set id，通过id标定convertview的种类
2.重写getViewTypeCount 和 getItemViewType 方法，来实现不同类型convertView的识别
（参考：http://stackoverflow.com/questions/5300962/getviewtypecount-and-getitemviewtype-methods-of-arrayadapter）
