### ISSUE TITLE
重构WebView

### ISSUE THREAD

**Issue by lkasdolka** [HalfdogStudio/BubbleDating#6]
现在的游泳日报太难看了。。

**Comment by reverland** [comment]
: (.......太难看

**Comment by lkasdolka** [comment]
现在的效果：

网易新闻webview的效果：

嗯，主要就是两边的空白。

459127552@qq.com

发件人： reverland
发送时间： 2015-06-02 17:21
收件人： HalfdogStudio/BubbleDating
抄送： Andy Liu
主题： Re: [BubbleDating] 重构WebView (#6)
: (.......太难看

**Comment by reverland** [comment]
https://github.com/reverland/topswim/issues/1 已修复移动端显示问题

**Comment by lkasdolka** [comment]
well done , buddy~
我这边显示也正常了

459127552@qq.com

发件人： reverland
发送时间： 2015-08-13 11:33
收件人： HalfdogStudio/BubbleDating
抄送： Andy Liu
主题： Re: [BubbleDating] 重构WebView (#6)
reverland/topswim#1 已修复移动端显示问题
―

**Comment by lkasdolka** [comment]
有空更新一下啊，都4个月没动静了。。

459127552@qq.com

发件人： reverland
发送时间： 2015-08-13 11:33
收件人： HalfdogStudio/BubbleDating
抄送： Andy Liu
主题： Re: [BubbleDating] 重构WebView (#6)
reverland/topswim#1 已修复移动端显示问题

**Comment by reverland** [comment]
更新了哈哈哈，考虑用javascript重新写爬虫，把游泳日报重构下
